[default]
BABEL_DEFAULT_LOCALE = "en"
BABEL_TRANSLATION_DIRECTORIES = "../translations"
BABEL_SUPPORTED_LOCALES = [
    "de",
    "en",
    "fr",
    "es",
    "pt",
    "it",
    "nl",
    "pl",
    "ru",
    "zh",
    "ja",
    "ko",
    "ar",
    "tr",
    "sv",
    "cs",
    "hu",
]
