[default]
# Default configuration
HOST = "127.0.0.1"
PORT = 5000
CALLBACK_PORT = 19999

DOMAIN = "x2fa.dev.inqbus.de"
ORIGIN = "https://x2fa.dev.inqbus.de"
NAME = "X2FA"

[production]
HOST = "prod.example.com"
PORT = 8000

DOMAIN = "prod.example.com"
ORIGIN = "https://prod.example.com"


[testing]
HOST = "127.0.0.1"
PORT = 5098

DOMAIN = "localhost"
ORIGIN = "https://localhost"
