"""Demo RP setup screen — registers demo-rp as an OIDC client and issues its cert."""

import os
import socket
import subprocess
from pathlib import Path

from textual import work
from textual.app import ComposeResult
from textual.containers import Container
from textual.screen import Screen
from textual.widgets import Button, Collapsible, Footer, Header, Input, Log, Markdown, Static

_HELP_TEXT = """\
## Demo Relying Party Setup

The demo RP (`demo_rp/app.py`) is a small Flask application that simulates an OIDC
relying party for end-to-end testing of the full authentication flow.

### What this screen does

1. **Register the demo-rp CA** — calls `flask add-ca demo-rp-ca <ca_cert>` to make
   the installation CA trusted for demo-rp client certificates. *(Only for PKI methods)*
2. **Register the demo-rp client** — calls `flask add-client demo-rp
   http://localhost:<port>/callback --method <your-auth-method>`.
3. **Issue client certificate** — signs a new cert with the CA and writes
   `demo_rp/demo-rp.cert.pem` and `demo_rp/demo-rp.key.pem`. *(Only for tls_client_auth)*

### After setup

Edit `demo_rp/demo_rp_settings.toml` to configure your auth method and start the demo RP:

```
uv run python demo_rp/app.py
```

Open `http://localhost:<port>` in a browser, click **Verify 2FA** or **Setup 2FA**.

### Supported Authentication Methods

| Method | Required Config | Description |
|---|---|---|
| `tls_client_auth` | `CLIENT_CERT_PATH`, `CLIENT_KEY_PATH` | CA-signed mTLS certificate (recommended) |
| `private_key_jwt` | `CLIENT_CERT_PATH`, `CLIENT_KEY_PATH`, `JWKS_URI` | JWT with certificate chain |
| `self_signed_tls_client_auth` | `CLIENT_CERT_PATH`, `CLIENT_KEY_PATH`, `CLIENT_SELF_SIGNED_CERT_PATH` | Self-signed cert fingerprint |
| `client_secret_jwt` | `CLIENT_CERT_PATH`, `CLIENT_KEY_PATH`, `CLIENT_SECRET` | JWT signed with shared secret |
| `client_secret_post` | `CLIENT_SECRET` | Secret in POST body |
| `client_secret_basic` | `CLIENT_SECRET` | HTTP Basic auth |

### Requirements

- X2FA must already be running and reachable.
- The demo RP will automatically detect your installed auth method and configure itself.
- For PKI methods (tls_client_auth, private_key_jwt, self_signed_tls_client_auth), a CA must be available.
- For secret methods (client_secret_*), the installer will append your secret to the settings file.
"""

_SETTINGS_TEMPLATE = """\
# Demo RP configuration — generated by the X2FA installer.
# Adjust X2FA_URL and DEMO_RP_URL to match your deployment.
SECRET_KEY        = "change-me-demo-rp-secret"
HOST              = "127.0.0.1"
PORT              = {port}
X2FA_URL          = "https://{domain}"
DEMO_RP_URL       = "http://localhost:{port}"
CLIENT_AUTH_METHOD = "{auth_method}"
CLIENT_CERT_PATH  = "demo-rp.cert.pem"
CLIENT_KEY_PATH   = "demo-rp.key.pem"
# CLIENT_SELF_SIGNED_CERT_PATH = "/path/to/self_signed.pem"  # for self_signed_tls_client_auth
# JWKS_URI         = "https://example.com/.well-known/jwks.json"  # for private_key_jwt
# CLIENT_SECRET    = "your-64-char-secret"  # for client_secret_* methods
"""

_PREFERENCES_HINT = """\
Preflight checks will verify:
- Port {port} is available for the demo RP
- X2FA is reachable at {domain}
- demo_rp directory is writable
- demo_rp_settings.toml can be written

Click **Set up Demo RP** to begin.
"""


class DemoRPScreen(Screen):
    BINDINGS = [("f1", "toggle_help", "Help")]

    def action_toggle_help(self) -> None:
        self.query_one("#help_panel", Collapsible).collapsed ^= True

    def compose(self) -> ComposeResult:
        cfg = self.app.config
        ca_cert = cfg.effective_ca_cert(cfg.ca_action)

        yield Header()
        with Container(id="panel"):
            yield Static("Demo Relying Party Setup", classes="screen-title")
            with Collapsible(title="Help  (F1)", id="help_panel", collapsed=True):
                yield Markdown(_HELP_TEXT)

            if not ca_cert:
                yield Static(
                    "[yellow]⚠  No CA certificate available.[/]\n"
                    "The demo RP setup requires a PKI-based installation\n"
                    "(tls_client_auth or private_key_jwt).\n"
                    "Go back and re-run the installer with one of those methods.",
                    markup=True,
                    classes="hint",
                )
                with Container(id="buttons"):
                    yield Button("← Back", id="back", variant="default")
                yield Footer()
                return

            domain = cfg.domain or "your-x2fa-domain.example.com"
            yield Static("Demo RP port:", classes="field-label")
            yield Input(value="5099", id="port", placeholder="5099")
            yield Static(
                "  The demo RP will listen on http://localhost:<port>.\n"
                "  The callback URL http://localhost:<port>/callback will be registered.",
                classes="hint",
            )
            yield Static(
                _PREFERENCES_HINT.format(port=5099, domain=domain),
                id="preflight_hint",
                markup=True,
                classes="hint",
            )

            yield Log(id="log", auto_scroll=True, highlight=True)

            with Container(id="buttons"):
                yield Button("← Back",          id="back",  variant="default")
                yield Button("Set up Demo RP →", id="run",   variant="primary")
                yield Button("Done",            id="done",  variant="success", disabled=True)
        yield Footer()

    def on_mount(self) -> None:
        self._log = self.query_one("#log", Log)

    def _write(self, line: str) -> None:
        self._log.write_line(line)

    # ── Background worker ─────────────────────────────────────────────────

    @work(thread=True)
    def _run_setup(self, port: int) -> None:
        from installer.ca import issue_client_cert
        from installer.runner import add_ca, add_client

        cfg = self.app.config

        def log(text: str) -> None:
            self.app.call_from_thread(self._write, text)

        def disable_run() -> None:
            self.query_one("#run", Button).disabled = True

        def enable_run() -> None:
            self.query_one("#run", Button).disabled = False

        self.app.call_from_thread(disable_run)

        # Preflight checks
        log("── Preflight checks ─────────────────────────")
        domain = cfg.domain or cfg.domain or "your-x2fa-domain.example.com"
        if not self._run_preflight_checks(port, domain, log):
            log("[red]Aborting — fix the errors above and try again.[/]")
            self.app.call_from_thread(enable_run)
            return
        log("[green]Continuing with setup...[/]")

        from x2fa import paths
        ca_cert = cfg.effective_ca_cert(cfg.ca_action)
        redirect_uri = f"http://localhost:{port}/callback"
        output_dir = paths.get_home() / "demo_rp"
        auth_method = cfg.client_auth_method

        # Step 1 — register CA (only for PKI methods)
        log("── Register demo-rp-ca ──────────────────────")
        if auth_method in {"tls_client_auth", "private_key_jwt", "self_signed_tls_client_auth"}:
            from installer.runner import init_db, init_keys
            init_db(str(paths.db_path()))
            init_keys(str(paths.config_dir()))
            ok, out = add_ca("demo-rp-ca", ca_cert, str(paths.config_dir()))
            for line in (out or "").splitlines():
                log(f"  {line}")
            if not ok:
                log("[red]Failed — aborting.[/]")
                self.app.call_from_thread(enable_run)
                return
            log("[green]  ✓  done[/]")
        else:
            log("[dim]SKIPPED — CA registration not needed for {auth_method}[/]")

        # Step 2 — register client
        log("── Register demo-rp client ──────────────────")
        ok, out = add_client(
            "demo-rp", redirect_uri, auth_method, str(paths.config_dir())
        )
        for line in (out or "").splitlines():
            log(f"  {line}")
        if not ok:
            log("[red]Failed — aborting.[/]")
            self.app.call_from_thread(enable_run)
            return
        log("[green]  ✓  done[/]")

        # Step 3 — issue client certificate (only for PKI methods)
        if auth_method in {"tls_client_auth", "self_signed_tls_client_auth"}:
            log("── Issue demo-rp client certificate ─────────")
            try:
                cert_paths = issue_client_cert(
                    "demo-rp",
                    ca_cert,
                    paths.ca_key_path(),
                    output_dir,
                )
                for k, v in cert_paths.items():
                    log(f"  {k}: {v}")
                log("[green]  ✓  done[/]")
            except Exception as exc:
                log(f"[red]Failed: {exc}[/]")
                self.app.call_from_thread(enable_run)
                return
        else:
            log("[dim]SKIPPED — Client cert not needed for {auth_method}[/]")

        # Step 4 — write demo_rp_settings.toml
        log("── Write demo_rp_settings.toml ──────────────")
        try:
            from x2fa import paths
            settings_path = paths.get_home() / "demo_rp" / "demo_rp_settings.toml"
            template_args = {
                "port": port,
                "domain": cfg.domain or "your-x2fa-domain.example.com",
                "auth_method": auth_method,
            }
            settings_path.write_text(
                _SETTINGS_TEMPLATE.format(**template_args)
            )
            
            # For secret methods, append the secret
            if auth_method in {"client_secret_jwt", "client_secret_post", "client_secret_basic"}:
                settings_path.write_text(
                    settings_path.read_text() + f"\nCLIENT_SECRET = \"{cfg.client_secret}\"\n"
                )
            
            log(f"  Written: {settings_path}")
            log("[green]  ✓  done[/]")
        except OSError as exc:
            log(f"[yellow]  ⚠  Could not write settings: {exc}[/]")

        log("")
        log("[green bold]Demo RP setup complete.[/]")
        log(f"  Start with:  uv run python demo_rp/app.py")
        log(f"  Open:        http://localhost:{port}")
        self.app.call_from_thread(self._on_done)

    def _on_done(self):
        self.query_one("#run").disabled = True
        self.query_one("#back").disabled = False
        self.query_one("#done").disabled = False

    def on_input_changed(self, event: Input.Changed) -> None:
        if event.input.id == "port":
            port = self.query_one("#port", Input).value.strip()
            if port and self.app.config.domain:
                port = int(port)
                domain = self.app.config.domain
                self.query_one("#preflight_hint", Static).update(
                    _PREFERENCES_HINT.format(port=port, domain=domain)
                )

    def _run_preflight_checks(self, port: int, domain: str, log_func) -> bool:
        """Run preflight checks before starting setup."""
        ok, errors = self._check_demo_rp_preflights(port, domain)
        if ok:
            log_func("[green]✓  All preflight checks passed[/]")
        else:
            log_func("[red]✗  Preflight checks failed:[/]")
            for error in errors:
                log_func(f"  [red]  {error}[/]")
            return False
        return True

    # ── Buttons ───────────────────────────────────────────────────────────

    def on_button_pressed(self, event: Button.Pressed) -> None:
        match event.button.id:
            case "back":
                self.app.pop_screen()
            case "run":
                if self.query_one("#run", Button).disabled:
                    return
                try:
                    port = int(self.query_one("#port", Input).value.strip())
                except ValueError:
                    self.notify("Port must be a number.", severity="error")
                    return
                self._run_setup(port)
            case "done":
                self.app.pop_screen()
