"""Demo RP setup screen — registers demo-rp as an OIDC client and issues its cert."""

from textual import work
from textual.app import ComposeResult
from textual.containers import Container
from textual.screen import Screen
from textual.widgets import Button, Collapsible, Footer, Header, Input, Log, Markdown, Static

_HELP_TEXT = """\
## Demo Relying Party Setup

The demo RP (`demo_rp/app.py`) is a small Flask application that simulates an OIDC
relying party for end-to-end testing of the full authentication flow.

### What this screen does

1. **Register the demo-rp CA** — calls `flask add-ca demo-rp-ca <ca_cert>` to make
   the installation CA trusted for demo-rp client certificates.
2. **Register the demo-rp client** — calls `flask add-client demo-rp
   http://localhost:<port>/callback --method tls_client_auth`.
3. **Issue the client certificate** — signs a new cert with the CA and writes
   `demo_rp/demo-rp.cert.pem` and `demo_rp/demo-rp.key.pem`.

### After setup

Edit `demo_rp/demo_rp_settings.toml` to set `X2FA_URL` and `DEMO_RP_URL`, then start
the demo RP:

```
uv run python demo_rp/app.py
```

Open `http://localhost:<port>` in a browser, click **Verify 2FA** or **Setup 2FA**.

### Requirements

- X2FA must already be running and reachable.
- The installation must have used a PKI auth method (`tls_client_auth` or
  `private_key_jwt`) so that a CA key is available to sign the demo-rp cert.
"""

_SETTINGS_TEMPLATE = """\
# Demo RP configuration — generated by the X2FA installer.
# Adjust X2FA_URL and DEMO_RP_URL to match your deployment.
SECRET_KEY        = "change-me-demo-rp-secret"
HOST              = "127.0.0.1"
PORT              = {port}
X2FA_URL          = "https://{domain}"
DEMO_RP_URL       = "http://localhost:{port}"
CLIENT_CERT_PATH  = "demo-rp.cert.pem"
CLIENT_KEY_PATH   = "demo-rp.key.pem"
"""


class DemoRPScreen(Screen):
    BINDINGS = [("f1", "toggle_help", "Help")]

    def action_toggle_help(self) -> None:
        self.query_one("#help_panel", Collapsible).collapsed ^= True

    def compose(self) -> ComposeResult:
        cfg = self.app.config
        ca_cert = cfg.effective_ca_cert()

        yield Header()
        with Container(id="panel"):
            yield Static("Demo Relying Party Setup", classes="screen-title")
            with Collapsible(title="Help  (F1)", id="help_panel", collapsed=True):
                yield Markdown(_HELP_TEXT)

            if not ca_cert:
                yield Static(
                    "[yellow]⚠  No CA certificate available.[/]\n"
                    "The demo RP setup requires a PKI-based installation\n"
                    "(tls_client_auth or private_key_jwt).\n"
                    "Go back and re-run the installer with one of those methods.",
                    markup=True,
                    classes="hint",
                )
                with Container(id="buttons"):
                    yield Button("← Back", id="back", variant="default")
                yield Footer()
                return

            yield Static("Demo RP port:", classes="field-label")
            yield Input(value="5099", id="port", placeholder="5099")
            yield Static(
                "  The demo RP will listen on http://localhost:<port>.\n"
                "  The callback URL http://localhost:<port>/callback will be registered.",
                classes="hint",
            )

            yield Log(id="log", auto_scroll=True, highlight=True)

            with Container(id="buttons"):
                yield Button("← Back",          id="back",  variant="default")
                yield Button("Set up Demo RP →", id="run",   variant="primary")
        yield Footer()

    def on_mount(self) -> None:
        self._log = self.query_one("#log", Log)

    def _write(self, line: str) -> None:
        self._log.write_line(line)

    # ── Background worker ─────────────────────────────────────────────────

    @work(thread=True)
    def _run_setup(self, port: int) -> None:
        from installer.ca import issue_client_cert
        from installer.runner import add_ca, add_client

        cfg = self.app.config

        def log(text: str) -> None:
            self.app.call_from_thread(self._write, text)

        def disable_run() -> None:
            self.query_one("#run", Button).disabled = True

        def enable_run() -> None:
            self.query_one("#run", Button).disabled = False

        self.app.call_from_thread(disable_run)

        ca_cert = cfg.effective_ca_cert()
        redirect_uri = f"http://localhost:{port}/callback"
        output_dir = str(cfg.install_root / "demo_rp")

        # Step 1 — register CA
        log("── Register demo-rp-ca ──────────────────────")
        ok, out = add_ca("demo-rp-ca", ca_cert, cfg.install_root)
        for line in (out or "").splitlines():
            log(f"  {line}")
        if not ok and "already" not in (out or "").lower():
            log("[red]Failed — aborting.[/]")
            self.app.call_from_thread(enable_run)
            return
        log("[green]  ✓  done[/]" if ok else "[yellow]  ⚠  already registered — continuing[/]")

        # Step 2 — register client
        log("── Register demo-rp client ──────────────────")
        ok, out = add_client(
            "demo-rp", redirect_uri, "tls_client_auth", cfg.install_root
        )
        for line in (out or "").splitlines():
            log(f"  {line}")
        if not ok and "already" not in (out or "").lower():
            log("[red]Failed — aborting.[/]")
            self.app.call_from_thread(enable_run)
            return
        log("[green]  ✓  done[/]" if ok else "[yellow]  ⚠  already registered — continuing[/]")

        # Step 3 — issue client certificate
        log("── Issue demo-rp client certificate ─────────")
        try:
            paths = issue_client_cert(
                "demo-rp",
                ca_cert,
                cfg.ca_key_path,
                output_dir,
            )
            for k, v in paths.items():
                log(f"  {k}: {v}")
            log("[green]  ✓  done[/]")
        except Exception as exc:
            log(f"[red]Failed: {exc}[/]")
            self.app.call_from_thread(enable_run)
            return

        # Step 4 — write demo_rp_settings.toml
        log("── Write demo_rp_settings.toml ──────────────")
        try:
            settings_path = cfg.install_root / "demo_rp" / "demo_rp_settings.toml"
            settings_path.write_text(
                _SETTINGS_TEMPLATE.format(
                    port=port,
                    domain=cfg.domain or "your-x2fa-domain.example.com",
                )
            )
            log(f"  Written: {settings_path}")
            log("[green]  ✓  done[/]")
        except OSError as exc:
            log(f"[yellow]  ⚠  Could not write settings: {exc}[/]")

        log("")
        log("[green bold]Demo RP setup complete.[/]")
        log(f"  Start with:  uv run python demo_rp/app.py")
        log(f"  Open:        http://localhost:{port}")

    # ── Buttons ───────────────────────────────────────────────────────────

    def on_button_pressed(self, event: Button.Pressed) -> None:
        match event.button.id:
            case "back":
                self.app.pop_screen()
            case "run":
                try:
                    port = int(self.query_one("#port", Input).value.strip())
                except ValueError:
                    self.notify("Port must be a number.", severity="error")
                    return
                self._run_setup(port)
